// 1. ADD THIS IMPORT AT THE VERY TOP
import { ClerkProvider } from "@clerk/nextjs";

import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      publishableKey="pk_test_Z2FtZS1saXphcmQtNzcuY2xlcmsuYWNjb3VudHMuZGV2JA"
      signInFallbackRedirectUrl="/register"
      signUpFallbackRedirectUrl="/register"
      signInForceRedirectUrl="/register"
      signUpForceRedirectUrl="/register"
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-slate-900`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
